import factory from "/Utils/element-factory.js"

export const div = factory("div")
export const a = factory("a")
export const span = factory("span")
export const strong = factory("strong")
export const main = factory("main")
export const img = factory("img")
export const h1 = factory("h1")
export const h2 = factory("h2")
export const h3 = factory("h3")
export const h4 = factory("h4")
export const h5 = factory("h5")
export const h6 = factory("h6")
export const button = factory("button")
export const input = factory("input")
export const label = factory("label")
export const select = factory("select")
export const option = factory("option")
export const textarea = factory("textarea")
